"""rename_user_table_to_users

Revision ID: 16df9bc09860
Revises: d5c5781588e0
Create Date: 2026-06-26 11:04:56.480867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16df9bc09860'
down_revision: Union[str, Sequence[str], None] = 'd5c5781588e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    op.execute('ALTER INDEX ix_user_email RENAME TO ix_users_email')
    op.execute('ALTER TABLE users RENAME CONSTRAINT user_pkey TO users_pkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.execute('ALTER INDEX ix_users_email RENAME TO ix_user_email')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT users_pkey TO user_pkey')
    # ### end Alembic commands ###
