"""add_requirement_ticket_table

Revision ID: 62715925287e
Revises: 16df9bc09860
Create Date: 2026-06-28 13:36:18.609092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62715925287e'
down_revision: Union[str, Sequence[str], None] = '16df9bc09860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_ticket_is_deleted'), 'requirement_ticket', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_requirement_ticket_ticket_number'), 'requirement_ticket', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_ticket_ticket_number'), table_name='requirement_ticket')
    op.drop_index(op.f('ix_requirement_ticket_is_deleted'), table_name='requirement_ticket')
    op.drop_table('requirement_ticket')
    # ### end Alembic commands ###
