"""Add TicketReopenRequest

Revision ID: 9672bbf2831f
Revises: ca6b22441218
Create Date: 2026-07-01 10:55:28.746065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9672bbf2831f'
down_revision: Union[str, Sequence[str], None] = 'ca6b22441218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reopen_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['requirement_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_reopen_request_ticket_id'), 'ticket_reopen_request', ['ticket_id'], unique=False)
    op.alter_column('requirement_ticket', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requirement_ticket', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_ticket_reopen_request_ticket_id'), table_name='ticket_reopen_request')
    op.drop_table('ticket_reopen_request')
    # ### end Alembic commands ###
